### ISSUE TITLE
Feature request - DeepL free API support

### ISSUE THREAD

**Issue by maximejobin** [vibgyj/WPTranslationFiller#182]
The URL to connect to the free API is different from the paid one and is not supported by the extension. That would be great if it would work.

![image](https://user-images.githubusercontent.com/1080760/152227459-cb34fefb-8859-4f22-989c-93f6720c3b33.png)

**Comment by psmits1567** [comment]
Hi Maxime,

The reason that we use the Pro version is because at the time of development the free Api did not work with integrations. Also it has a limitation in the amount of characters to translate. And the quality of translations from the free version is less then from Pro.
But we will investigate if it is now possible to use a free licence for translation.
Keep following this channel.
Regards,
Peter

**Comment by psmits1567** [comment]
First tests reveal that translation is working with the Free account.
So we will make a test version that contains the possibility to test it.

**Comment by maximejobin** [comment]
Awesome! I'll wait for more info about the next version.

Thank you in advance!

**Comment by psmits1567** [comment]
Hi Maxime,

If you want to test this new feature, you can download and install this version:https://github.com/vibgyj/WPTranslationFiller/tree/Deepl-Free-integration
You can find the method to install in the Wiki
