### ISSUE TITLE
Extension suddenly crashed

### ISSUE THREAD

**Issue by sanjuacodez** [vibgyj/WPTranslationFiller#260]
It worked well before. But from couple of days before, I am getting an error like in the https://prnt.sc/DF9yQr6IYHJQ . Do you know what is the reason behind this? I haven't changed the settings. I am using Google translation(API is created and configured). Please refer https://prnt.sc/oYB8pyCtvWxM

**Comment by psmits1567** [comment]
Hi thanks for reporting this issue.
I have seen this happening before due to wrong responses from Google.
Could you try to figure out which sentence this error produces?
Try that by selecting one line first and then translate button
I have tested this with the latest branch "buildstatsnew" and Google, it produces no problems for my locale nl-NL
Also it is recommended to add at least one line within the fields pre translation replace and post translation replace
The format is : pages,pagina's for Dutch , so two verbs separated with a comma

I could happen because the original contains a non visible char

**Comment by sanjuacodez** [comment]
Hi,
Thanks for your response. I am not sure about the wrong responses from Google, because I am getting errors when I am using local translation as well. Initially, I tried version 1.6.14(from the chrome web store) but later I tried 1.6.16(from GitHub). 
I can see two errors when I am trying to use local translation. 
Errors I found(Not sure it helps you to sort this out):  https://prnt.sc/JzzukZ4VGejX and https://prnt.sc/_XsXr4kE_2qc

**Comment by psmits1567** [comment]
Uploaded the branch "buildstatsnew", can you test if that gives a warning, or if you already have solved your problem let me know

**Comment by sanjuacodez** [comment]
Apologies... I didn't check this as I was away from my desktop for a few days. Let me check and update you.

**Comment by sanjuacodez** [comment]
Hi @psmits1567,

No luck here.. :( I am still getting the same error. I am using "branchstatsnew" and cleared Mytrans and KeyStore DB.

**Comment by psmits1567** [comment]
After clearing the local database, did you refresh the addon via extensions? If so can you check that the database is present?
If it still does not work can you give me your locale value.
Which browser are you using?
Did you add values to the pre and post translation formfields?

**Comment by psmits1567** [comment]
Can you also try the following:
Open project
Go into the editor
Translate the line manually
Click add to database
Do not save thetranslation!
Refresh your screen
Go into the same line
Click on translate
Does that give you the translation added to the local database?
If that is the case then it is not a problem with the local database.
DeepL has also a free licence, it would be interesting to know if the problem does not exist with DeepL

**Comment by sanjuacodez** [comment]
Can you also try the following:
Open project
Go into the editor
Translate the line manually
Click add to the database
Do not save the translation!
Refresh your screen
Go into the same line
Click on translate
Does that give you the translation added to the local database?
If that is the case then it is not a problem with the local database.
//Yes. it is added to the database and clicking translate shows the same value.


DeepL has also a free licence, it would be interesting to know if the problem does not exist with DeepL
//I am from India and DeepL don't support India. I cannot create account from here :(

**Comment by psmits1567** [comment]
Ok this is interesting, as that shows it is not a database problem. If the translation can be saved and retrieved, then the database is working correctly.
You indicated that you are testing with "nl", the question is now does Google accept translation requests from India with locale "nl". What value did you setup before? Now I know you are from India I can perform some tests with the locale for India, because it eventually means that Google does no longer accept India for requests

**Comment by psmits1567** [comment]
I do not see a value for India in the supported Api language table, so which code did you us before? E.g. "nl" is Dutch, "fr" is for French

**Comment by sanjuacodez** [comment]
Yes, I am from India and I am adding translations(es, fr,nl etc) for our plugins from India. 

As far as now, I think this is a 403 error(Google is not authenticating this). By checking console, I am getting that error.

**Comment by sanjuacodez** [comment]
Really sorry for the mix-up. I understand the problem. As I said earlier, the translation API is somehow disabled in my google project. That is why we are getting this 403 error. I enabled the same and now, it's working.

Really appreciated your assistance for sort this out... 
And again apologies for my mistake...!!!
